apiVersion: v1
kind: Service
metadata:
  name: entidadequalquer-sql-svc
spec:
  type: NodePort
  ports:
    - port: 1433
      #targetPort: 1433
      nodePort: 31001
  selector: 
    app: entidadequalquer-sql