apiVersion: v1
kind: Service
metadata:
  name: entidadequalquer-svc
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort: 1433
      nodePort: 31002
  selector: 
    app: entidadequalquer-aplicacao